django/practice/posts/urls.py
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('', views.index, name='list'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
    path('<int:post_id>/edit/', views.edit, name='edit'),
    path('<int:post_id>/comments/create/', views.comments_create, name='comments_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete/', views.comments_delete, name='comments_delete'),
]

django/practice/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    #image = models.ImageField(blank=True)
    image = ProcessedImageField(
            upload_to='posts/images',
            processors=[Thumbnail(100,100)],
            format='JPEG',
            options={'quality':90}
        )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    

django/practice/posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment

# Create your views here.

def new(request):
    if request.method == 'POST':
        #create
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        
        post = Post(title=title, content=content, image=image)
        post.save()
        
        return redirect('posts:detail', post.pk)
    
    else:
        #new
        return render(request, 'new.html')
    

def index(request):
    posts = Post.objects.all()
    return render(request, 'index.html', {'posts':posts})

def detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    return render(request, 'detail.html', {'post':post})

def delete(request, post_id):
    if request.method == "POST":
        post = Post.objects.get(pk=post_id)
        post.delete()
        return redirect('posts:list')
        
    else:
        return render(request, 'delete.html')

def edit(request, post_id):
    post = Post.objects.get(pk=post_id)
    
    if request.method == 'POST':
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        post.save()
        return redirect('posts:detail', post.pk)
    
    else:
        return render(request, 'edit.html', {'post':post})
    

def comments_create(request, post_id):
    post = Post.objects.get(pk=post_id)
    content = request.POST.get('content')
    
    comment = Comment(post=post, content=content)
    comment.save()
    
    return redirect('posts:detail', post.pk)

def comments_delete(request, post_id, comment_id):
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    
    return redirect('posts:detail', post_id)

django/practice/posts/templates/delete.html
{% extends 'base.html' %}
{% block container %}
    <h1>삭제하시겠습니까?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="삭제"/>
    </form>
{% endblock %}

django/practice/posts/templates/detail.html
{% extends 'base.html' %}
{% block container %}
    <h1>Post detail</h1>
    <p> title: {{post.title}}</p>
    <p> content: {{post.content}}</p>
    <img src="{{ post.image.url }}"></img>
    
    <a href="{% url 'posts:list' %}"> Back to list</a>
    <a href="{% url 'posts:delete' post.pk %}"> delete </a>
    <a href="{% url 'posts:edit' post.pk %}"> Edit</a>
    
    <form action="{% url 'posts:comments_create' post.pk %}" method="post">
        {% csrf_token %}
        댓글 : <input type="text" name="content"/>
        <input type="submit" value="Submit"/>
    </form>
    
    <ul>
        {% for comment in post.comment_set.all %}
        <li> {{comment.content }} <a href="{% url 'posts:comments_delete' post.pk comment.pk %}">댓글 삭제</a></li>
        {% endfor %}
    </ul>
{% endblock %}

django/practice/posts/templates/edit.html
{% extends 'base.html' %}
{% block container %}
    <h1>Post Edit</h1>
    <form method='post'>
        {% csrf_token %}
        <input type="text" name="title" value="{{ post.title }}"/>
        <input type="text" name="content" value = "{{ post.content }}"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

django/practice/posts/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" />
    <title>Document</title>
</head>
<body>
    <h1>Index Detail</h1>
    <img src="{% static 'jango.jfif' %}"></img>
    <a href="{% url 'posts:new' %}"><p> 새글 쓰러 가기</p></a>
    <ul>
    {% for post in posts %}
        <li> <a href="{% url 'posts:detail' post.pk %}"> {{post.title}} </a> </li>
    {% endfor %}
    </ul>
</body>
</html>

django/practice/posts/templates/new.html
{% extends 'base.html' %}
{% block container %}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="title"/>
        <input type="text" name="content"/>
        <input type="file" name="image" accept="image/*"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}