django/exercise6/exercise6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('poll/', include('poll.urls')),
    path('admin/', admin.site.urls),
]

django/exercise6/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:q_id>/', views.detail, name='detail'),
    path('<int:q_id>/delete/',views.delete, name='delete'),
    path('<int:q_id>/choice/create/', views.choice_create, name='choice_create'),
    path('', views.index, name='index'),
]

django/exercise6/students/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('create/', views.create),
    path('new/', views.new),
    path('', views.index),
    path('<int:student_id>/', views.detail),
    path('delete/<int:student_id>/', views.delete),
    path('edit/<int:student_id>/', views.edit),
    path('update/<int:student_id>/', views.update),
]

django/exercise6/poll/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=100)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    votes = models.IntegerField()

django/exercise6/students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    age = models.TextField()
    uni = models.TextField()

django/exercise6/poll/views.py
from django.shortcuts import render, redirect
from .models import Question, Choice
# Create your views here.

def new(request):
    return render(request, 'new1.html')

def create(request):
    title = request.POST.get('title')
    question = Question(title=title)
    question.save()
    return redirect('poll:detail', question.pk)

def index(request):
    questions = Question.objects.all()
    return render(request, 'index1.html', {'questions':questions})

def detail(request, q_id):
    question = Question.objects.get(pk=q_id)
    return render(request, 'detail1.html', {'question': question})

def delete(request, q_id):
    question = Question.objects.get(pk=q_id)
    question.delete()
    return redirect('poll:index')

def choice_create(request, q_id):
    question = Question.objects.get(pk=q_id)
    content = request.POST.get('content')
    votes = request.POST.get('votes')
    
    choice = Choice(question = question, content=content, votes=votes)
    choice.save()
    
    return redirect('poll:detail', question.pk)

django/exercise6/students/views.py
from django.shortcuts import render, redirect
from .models import Student

# Create your views here.

def new(request):
    return render(request, 'new.html')

def create(request):
    name = request.POST.get('name')
    age = request.POST.get('age')
    uni = request.POST.get('uni')
    
    student = Student(name=name, age=age, uni=uni)
    student.save()

    return redirect(f'/students/{student.pk}')
    
def index(request):
    students = Student.objects.all()
    
    return render(request, 'index.html', {'students' :students})

def detail(request, student_id):
    student = Student.objects.get(pk=student_id)
    return render(request, 'detail.html', {'student':student})

def delete(request, student_id):
    student = Student.objects.get(pk=student_id)
    student.delete()
    return redirect('/students/')

def edit(request, student_id):
    student = Student.objects.get(pk=student_id)
    return render(request, 'edit.html', {'student':student})
    
def update(request, student_id):
    student = Student.objects.get(pk=student_id)
    student.name = request.POST.get('name')
    student.age = request.POST.get('age')
    student.uni = request.POST.get('uni')
    student.save()
    
    return redirect(f'/students/{student.pk}/')
    
    
    
    
    
    
    
    
    
    
    

django/exercise6/poll/templates/detail1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Detail</h1>
    <p> 투표주제: {{question.title}}</p>
    <a href="{% url 'poll:index' %}">back to list</a>
    <a href="{% url 'poll:delete' question.pk %}"> Delete </a>
    
    <form action="{% url 'poll:choice_create' question.pk %}" method="post">
        {% csrf_token %}
        <select name="content" id="">
            <option>한식</option>
            <option>중식</option>
            <option>일식</option>
        </select>
        <input type="text" name="votes"/>
        <input type="submit" value="Submit"/>
    
    <ul>
        {% for choice in question.choice_set.all %}
        <li> {{choice.content }}</li>
        <li> {{choice.votes }}</li>
        {% endfor %}
    </ul>
    
    
    </form>
</body>
</html>

django/exercise6/poll/templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> Index </h1>
    <a href="{% url 'poll:new' %}">새 글 작성하기</a>
    <ul>
        {% for question in questions %}
            <li><a href="{% url 'poll:detail' question.pk %}"> 투표주제: {{question.title}}</li></a>
        {% endfor %}
    </ul>

</body>
</html>

django/exercise6/poll/templates/new1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>내용 작성하기</h1>
    <form action="{% url 'poll:create' %}" method="post">
        {% csrf_token %}
        <input type="text" name="title"/>
        <input type="submit" value="Submit"/>
</form>
</body>
</html>

django/exercise6/students/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1> 정상적으로 POST되었습니다. </h1>
</body>
</html>

django/exercise6/students/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Student detail</h1>
    <p> name: {{student.name}}</p>
    <p> age: {{student.age}}</p>
    <p> uni: {{student.uni}}</p>
    <a href="/students/">back to list</a>
    <a href="/students/delete/{{student.pk}}/">Delete</a>
    <a href="/students/edit/{{student.pk}}/">Edit</a>
</body>
</html>

django/exercise6/students/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="/students/update/{{student.pk}}/" method="post">
        {% csrf_token %}
        <input type="text" name="name" value="{{student.name}}"/>
        <input type="text" name="age" value="{{student.age}}"/>
        <input type="text" name="uni" value="{{student.uni}}"/>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>

django/exercise6/students/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Students Index</h1>
    <ul>
    {% for student in students %}
        <li><a href="/students/{{student.pk}}">name: {{student.name}}</a></li>
    {% endfor %}
    </ul>
</body>
</html>

django/exercise6/students/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="/students/create/" method="post">
        {% csrf_token %}
        <input type="text" name="name"/>
        <input type="text" name="age"/>
        <input type="text" name="uni"/>
        <input type="submit" value="Submit"/>
    </form>
</body>
</html>